MadisonCountyCollaborationApplication/Pages/Dataset/ChartDisplay.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MadisonCountyCollaborationApplication.Pages.Dataset
{
    public class ChartDisplayModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MadisonCountyCollaborationApplication/Pages/Dataset/DatasetLanding.cshtml.cs
using MadisonCountyCollaborationApplication.Pages.DB;
using MadisonCountyCollaborationApplication.Pages.DataClasses;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;

namespace MadisonCountyCollaborationApplication.Pages.Dataset
{
    public class DatasetLandingModel : PageModel
    {
        [BindProperty]
        [Required]
        public int DatasetID { get; set; }
        public List<Datasets> DatasetList { get; set; }
        [BindProperty]
        public List<IFormFile> FileList { get; set; }
        public MadisonCountyCollaborationApplication.Pages.DataClasses.Attributes NewA { get; set; }
        public MadisonCountyCollaborationApplication.Pages.DataClasses.AttributeValue NewV { get; set; }



        public DatasetLandingModel()
        {
            DatasetList = new List<Datasets>();
        }

        public IActionResult OnGet()
        {
            //displaying datasets
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewData["LoginMessage"] = "Login for "
                    + HttpContext.Session.GetString("username")
                    + " successful!";

                SqlDataReader DatasetReader = DBClass.DatasetReader();
                while (DatasetReader.Read())
                {
                    DatasetList.Add(new Datasets
                    {
                        ID = Int32.Parse(DatasetReader["datasetID"].ToString()),
                        Name = DatasetReader["dataSetName"].ToString()

                    });
                }
                DBClass.MainDBconnection.Close();
                return Page();
            }
            else
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../User/Login");
            }
        }
        //adding datataset
        public IActionResult OnPostAsync()
        {
            String attributeName;
            int attributeID;
            String dataValue;
            //looping through each file
            foreach (var formFile in FileList)
            {
                if (formFile.Length > 0)
                {
                    // Ensure only CSV files are uploaded
                    if (!formFile.FileName.EndsWith(".csv"))
                    {
                        ModelState.AddModelError("FileList", "Only CSV files are allowed.");
                        return RedirectToPage("DatasetLanding");
                    }
                    // full path to file in temp location
                    var filePath = Directory.GetCurrentDirectory() + @"\wwwroot\fileupload\" + formFile.FileName;



                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        formFile.CopyTo(stream);
                    }
                    return RedirectToPage("FileHandling", new { filePath = filePath });
                   

                }
            }
            return RedirectToPage("DatasetLanding");
        }

        //selecting dataset
        public IActionResult OnPostSelect()
        {
            if (DatasetID != null && DatasetID > 0)
            {
                if (DBClass.DatasetExist(DatasetID))
                {
                    HttpContext.Session.SetInt32("datasetID", DatasetID);
                    DBClass.MainDBconnection.Close();
                    return RedirectToPage("ViewData");

                }
                else
                {
                    DBClass.MainDBconnection.Close();
                    ViewData["CollabNotExistMessage"] = "That collaboration does not exist.";
                    return OnGet();
                }

            }
            else
            {
                ViewData["CollabNotExistMessage"] = "That collaboration does not exist.";
                return OnGet();
            }
        }
    }
}

MadisonCountyCollaborationApplication/Pages/Dataset/MonteCarlo.cshtml.cs
//using iTextSharp.text.pdf.parser.clipper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plotly.NET.CSharp;
using Newtonsoft.Json;
using MadisonCountyCollaborationApplication.Pages.DataClasses;
using MathNet.Numerics.Random;
using MadisonCountyCollaborationApplication.Pages.DB;
using System.Data;


namespace MadisonCountyCollaborationApplication.Pages.Dataset
{
    public class MonteCarloModel : PageModel
    {
        [BindProperty]
        public int iterations { get; set; }
        [BindProperty]
        public int years { get; set; }
        [BindProperty]
        public Parameters Taxes { get; set; }
        [BindProperty]
        public Parameters Gov { get; set; }
        [BindProperty]
        public Parameters Other { get; set; }
        [BindProperty]
        public double confidenceInterval { get; set; }
        public string ChartConfigJson { get; private set; }
        [BindProperty]
        public string ProcessName { get; set; }
        [BindProperty]
        public string DatasetName { get; set; }
        [BindProperty]
        public int datasetID { get; set; }


        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewData["LoginMessage"] = "Login for "
                    + HttpContext.Session.GetString("username")
                    + " successful!";
                //get process name
                ProcessName = HttpContext.Session.GetString("processName");
                datasetID = (int)HttpContext.Session.GetInt32("datasetID");
                DatasetName = DBClass.ExtractDatasetName(datasetID);
                DBClass.MainDBconnection.Close();
                return Page();
            }
            else
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("/Login");
            }
        }
        public IActionResult OnPost()
        {
            double[] results = RevenueSimple(iterations, years, Taxes, Gov, Other);
            var chart = Chart.Histogram<double, double, string>(X: results)
                .WithXAxisStyle<double, double, string>(Title: Plotly.NET.Title.init("Revenue"))
                .WithYAxisStyle<double, double, string>(Title: Plotly.NET.Title.init("Frequency"));
            
                double[] CI = new Simulation().ConfidenceInterval(results, confidenceInterval);

                string confidence = "[" + CI[0] + "," + CI[1] + "]";
            
            //var chart = Chart.Histogram(x:results.ToList());

            //.WithTraceInfo("Data Points", ShowLegend: true)
            //.WithXAxisStyle<double, double, string>(Title: Plotly.NET.Title.init("Independent Variable"))
            //.WithYAxisStyle<double, double, string>(Title: Plotly.NET.Title.init("Dependent Variable"));
            var settings = new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore, // Ignore circular references
                TypeNameHandling = TypeNameHandling.None, // Additional setting to avoid $type insertion
                Formatting = Formatting.None // Use None for smaller payload; use Indented for readable JSON
            };

            var chartJson = JsonConvert.SerializeObject(chart, settings);
            ChartConfigJson = chartJson;
            var response = new
            {
                Data = new { Fields = new[] { results } },
                Confidence = confidence
                    // This is your existing data structure
            };
            var jsonResponse = JsonConvert.SerializeObject(response, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                TypeNameHandling = TypeNameHandling.None,
                Formatting = Formatting.None
            });
            return Content(jsonResponse, "application/json");
        }
        public IActionResult OnPostRevComp()
        {
            return RedirectToPage("MonteCarloRevComp");
        }
        public IActionResult OnPostExpense()
        {
            return RedirectToPage("MonteCarloExpense");
        }
        public IActionResult OnPostHelp()
        {
            return RedirectToPage("MonteCarloHelp");
        }
        //parameters follow: (current value, distribution name, statistical parameters)

        public double[] RevenueSimple(int iterations, int years, Parameters taxParameters,
            Parameters intergovernmentalParameters, Parameters otherParameters)
        {
            double[] revenues = new double[iterations];
            Simulation sim = new Simulation();
            //assigning distribution
            DataClasses.Distribution dist1 = sim.AssignDistribution(taxParameters);
            Console.WriteLine("Taxes");
            DataClasses.Distribution dist2 = sim.AssignDistribution(intergovernmentalParameters);
            Console.WriteLine("Gov");
            DataClasses.Distribution dist3 = sim.AssignDistribution(otherParameters);
            Console.WriteLine("Other");

            //conducting simulation
            double tax;
            double gov;
            double other;
            for (int i = 0; i < iterations; i++)
            {
                tax = sim.GenerateResult(dist1, Convert.ToDouble(taxParameters.initial), taxParameters.growth, years);
                gov = sim.GenerateResult(dist2, Convert.ToDouble(intergovernmentalParameters.initial), intergovernmentalParameters.growth, years);
                other = sim.GenerateResult(dist3, Convert.ToDouble(otherParameters.initial), otherParameters.growth, years);
                revenues[i] = tax + gov + other;
            }
           
            
            return revenues;
        }

    }
}

MadisonCountyCollaborationApplication/Pages/Dataset/MonteCarloHelp.cshtml.cs
using MadisonCountyCollaborationApplication.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MadisonCountyCollaborationApplication.Pages
{
    public class MonteCarloHelpModel : PageModel
    {
        [BindProperty]
        public int datasetID { get; set; }
        [BindProperty]
        public int DatasetName { get; set; }
        public void OnGet()
        {
            datasetID = (int)HttpContext.Session.GetInt32("datasetID");
            //DatasetName = DBClass.ExtractDatasetName(datasetID);
            DBClass.MainDBconnection.Close();
        }
    }
}

MadisonCountyCollaborationApplication/Pages/Dataset/ViewData.cshtml.cs
using MadisonCountyCollaborationApplication.Pages.DataClasses;
using MadisonCountyCollaborationApplication.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data.SqlClient;


namespace MadisonCountyCollaborationApplication.Pages.Dataset
{
    public class ViewDataModel : PageModel
    {
        public class CollaborationOption
        {
            public int CollabID { get; set; }
            public string Name { get; set; }
        }


        [BindProperty]
        public string AnalysisType { get; set; }
        [BindProperty]
        public string Independent { get; set; }
        [BindProperty]
        public string Dependent { get; set; }
        public List<Attributes> AttributeList { get; set; }
        
        [BindProperty]
        public int DatasetID { get; set; }
        [BindProperty]
        public string DatasetName { get; set; }

        public DataTable Data { get; private set; }

        [BindProperty]
        public int SelectedCollabID { get; set; } // Binds the selected collaboration ID
        public List<SelectListItem> CollaborationOptions { get; set; } // Holds dropdown options

        [BindProperty]
        public string ProcessName { get; set; }
        [BindProperty]
        public string DatasetNameDisplay { get; set; }
        public ViewDataModel()
        {
            AttributeList = new List<Attributes>();
        }
        public IActionResult OnGet(int datasetID)
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewData["LoginMessage"] = "Login for "
                    + HttpContext.Session.GetString("username")
                    + " successful!";
                //get process name
                ProcessName = HttpContext.Session.GetString("processName");

                //get dataset name
                DatasetNameDisplay = HttpContext.Session.GetString("datasetName");
                DatasetID = datasetID;
                //DatasetID = (int)HttpContext.Session.GetInt32("datasetID");
                HttpContext.Session.SetInt32("datasetID", DatasetID);
                DatasetName = DBClass.ExtractDatasetName(DatasetID);
                DBClass.MainDBconnection.Close();
                Data = DBClass.FetchDataForTable(DatasetName);
                DBClass.MainDBconnection.Close();

                

                return Page();
            }
            else
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("/Login");
            }

            
        }

        public IActionResult OnPostAddCollabData()
        {
            string sqlQuery = @"
                INSERT INTO DataAssists
                (collabID, datasetID)
                VALUES (" + SelectedCollabID + "," + DatasetID + ");";

            DBClass.GeneralInsertQuery(sqlQuery);
            return Page();
        }

        public IActionResult OnPostRedirectToAnalysis()
        {
            string test = "SingleRegression";
            Console.WriteLine(AnalysisType == test);
            switch (AnalysisType)
            {
                case "SingleRegression":
                    // Redirect to the Single Regression analysis page
                    return RedirectToPage("SingleRegression");
                case "MultiRegression":
                    // Redirect to the Multi Regression analysis page
                    return RedirectToPage("MultiRegression");
                case "Simulation":
                    // Redirect to the Multi Regression analysis page
                    return RedirectToPage("MonteCarloSimple");
                case "TylerRegression":
                    return RedirectToPage("TylerRegression");
                default:
                    // Optional: Handle unknown selection or return to the current page with a message
                    return Page();
            }
        }
    }
}
    

MadisonCountyCollaborationApplication/Pages/Dataset/ChartDisplay.cshtml
@page
@model MadisonCountyCollaborationApplication.Pages.Dataset.ChartDisplayModel
@{
}

<div class="text-center">
    <h1 class="display-4">Chart Display</h1>
    <div id="chart"></div>
</div>

<h2>Plotly Example</h2>

<div id="plotDiv" style="width:100%;height:500px;"></div>

@section Scripts {
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
        var data = [{
            x: [1, 2, 3, 4, 5],
            y: [10, 20, 30, 40, 50],
            mode: 'lines+markers',
            type: 'scatter'
        }];

        var layout = {
            title: 'Sample Plot',
            xaxis: {
                title: 'X Axis',
            },
            yaxis: {
                title: 'Y Axis',
            }
        };

        Plotly.newPlot('plotDiv', data, layout);
    </script>
}

MadisonCountyCollaborationApplication/Pages/Dataset/DatasetLanding.cshtml
@page
@model MadisonCountyCollaborationApplication.Pages.Dataset.DatasetLandingModel



<div class="text-center">
    <h1 class="display-4">View Datasets</h1>
</div>
<div class="row">
    <div class="col-md-9">
        @* showing all datasets *@
        <form asp-page-handler="Select" method="post" id="dataForm">
            <input type="hidden" name="DatasetID" id="dataIdInput" value="" />
            <div class="box-table">
                @{
                    foreach (var prod in Model.DatasetList)
                    {
                        <div class="card" data-collab-id="@prod.ID" onclick="selectDataset(@prod.ID)">
                            <div class="card-header">
                                @prod.Name
                            </div>
                        </div>
                    }
                }
            </div>
        </form>

        @section Scripts {
            <script>
                function selectDataset(dataId) {
                    // Set the value of the hidden input to the dataset ID
                    document.getElementById('dataIdInput').value = dataId;
                    // Submit the form
                    document.getElementById('dataForm').submit();
                }
            </script>
        }
        <br />
        <div class="row">
            <div class="col-md-6">
                @* allowing to add dataset *@
                <form method="post" enctype="multipart/form-data" asp-action="FileUpload">
                    <div class="form-group">
                        <div class="col-md-10">
                            <input asp-for="FileList" type="file" multiple class="btn btn-primary" />
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" value="Upload File(s)" class="btn btn-primary" />
                        </div>
                    </div>
                </form>

            </div>
            
        </div>
    </div>

    
</div>


@* <div class="datasets"
<ul>
    @{
        foreach (var dataset in Model.DatasetList)
        {
            <li> <a asp-page="ViewData" asp-route-datasetID="@dataset.ID">@dataset.Name</a> </li>
        }
    }
</ul>
 *@

MadisonCountyCollaborationApplication/Pages/Dataset/FileHandling.cshtml
@page
@model MadisonCountyCollaborationApplication.Pages.Dataset.FileHandlingModel
@{
}

@{
    string imagesDir = Directory.GetCurrentDirectory(); // <!-- Get information about files in the directory -->
    imagesDir += @"\wwwroot\fileupload\";
    <p>@imagesDir</p>
    <br />
    DirectoryInfo imagesFolder = new DirectoryInfo(imagesDir);

    var fileListing = imagesFolder.GetFiles();

    foreach (var file in fileListing) // Loop through each file in the directory and display as a link
    {
        <a href="/fileupload/@file.Name" target="_blank">@file.Name</a>
        <br />
    }
}

@if (!ModelState.IsValid) // <!-- Display error messages if model state is not valid -->
{
    foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
    {
        <div class="alert alert-danger">@error.ErrorMessage</div>
    }
}

@if (TempData["SuccessMessage"] != null) // <!-- Display success message if TempData contains it -->
{
    <div class="alert alert-success">@TempData["SuccessMessage"]</div>
}

MadisonCountyCollaborationApplication/Pages/Dataset/MonteCarlo.cshtml
@page
@model MadisonCountyCollaborationApplication.Pages.Dataset.MonteCarloModel
@{
}

@* breadcrum navigation *@
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-page="../Home">Home</a></li>
        <li class="breadcrumb-item"><a asp-page="../Process/Index">@Model.ProcessName</a></li>
        <li class="breadcrumb-item"><a asp-page="ViewData" asp-route-datasetID="@Model.datasetID">@Model.DatasetName.TrimStart('_').Replace("_", " ")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Monte Carlo</li>
    </ol>
</nav>
<div class="text-center">
    <h1 class="display-4">Simple Rev Simulation</h1>
</div>
<br />
<div class="row">
    <div class="col-md-4">
        <form asp-page-handler="RevComp" method="post">
            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit">Complicated Revenue</button>
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <form asp-page-handler="Help" method="post">
            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit">Help</button>
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <form asp-page-handler="Expense" method="post">
            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit">Expenses</button>
            </div>
        </form>
    </div>
</div>
<br />
<form method="post" id="dataForm">
    <div class="row">
        <div class="col-md-4">
            Number of iterations:
            <input type="number" class="form-control" placeholder="Iterations" aria-label="Iterations" asp-for="iterations">
        </div>
        <div class="col-md-4">
            Number of Years:
            <input type="number" class="form-control" placeholder="Years" aria-label="Years" asp-for="years">
        </div>
        <div class="col-md-4">
            <label class="input-group-text" for="confidence">Significance Level</label>
            <div class="input-group">
                <select class="form-select" id="confidence" aria-label="Select distribution" asp-for="confidenceInterval">
                    <option selected value=90>90</option>
                    <option value="95">95</option>
                    <option value="99">99</option>
                </select>
            </div>
        </div>
    </div>
    <br />

    <h4 class="display-4">Taxes: </h4>
    <div class="row">
        <div class="col-md-2">
            Initial Value:
            <input type="number" class="form-control" placeholder="Initial Value" aria-label="Iterations" asp-for="Taxes.initial">
        </div>

        <div class="col-md-2">
            <label class="input-group-text" for="Taxes_dist">Distribution</label>
            <div class="input-group">
                <select class="form-select" id="Taxes_dist" aria-label="Select distribution" asp-for="Taxes.dist">
                    <option selected value="Constant">Constant</option>
                    <option value="Uniform">Uniform</option>
                    <option value="Triangular">Triangular</option>
                    <option value="Normal">Normal</option>
                    <option value="Lognormal">Lognormal</option>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <label class="input-group-text" for="Taxes_growth">Growth Type</label>
            <div class="input-group">
                <select class="form-select" id="Taxes_growth" aria-label="Select Growth" asp-for="Taxes.growth">
                    <option value="Constant">Constant Growth</option>
                    <option value="Nonconstant">Nonconstant Growth</option>
                    <option selected value="None">No Growth</option>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="mean/min" aria-label="Iterations" asp-for="Taxes.param1">
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="variance/max" aria-label="Iterations" asp-for="Taxes.param2">
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="Most Likely" aria-label="Iterations" asp-for="Taxes.param3">
        </div>
    </div>
    <br />

    <h4 class="display-4">Intergovernmental: </h4>
    <div class="row">
        <div class="col-md-2">
            Initial Value:
            <input type="number" class="form-control" placeholder="Initial Value" aria-label="Iterations" asp-for="Gov.initial">
        </div>

        <div class="col-md-2">
            <label class="input-group-text" for="Gov_dist">Distribution</label>
            <div class="input-group">
                <select class="form-select" id="Gov_dist" aria-label="Select distribution" asp-for="Gov.dist">
                    <option selected value="Constant">Constant</option>
                    <option value="Uniform">Uniform</option>
                    <option value="Triangular">Triangular</option>
                    <option value="Normal">Normal</option>
                    <option value="Lognormal">Lognormal</option>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <label class="input-group-text" for="Gov_growth">Growth Type</label>
            <div class="input-group">
                <select class="form-select" id="Gov_growth" aria-label="Select Growth" asp-for="Gov.growth">
                    <option value="Constant">Constant Growth</option>
                    <option value="Nonconstant">Nonconstant Growth</option>
                    <option selected value="None">No Growth</option>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="mean/min" aria-label="Iterations" asp-for="Gov.param1">
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="variance/max" aria-label="Iterations" asp-for="Gov.param2">
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="Most Likely" aria-label="Iterations" asp-for="Gov.param3">
        </div>
    </div>
    <br />

    <h4 class="display-4">Other: </h4>
    <div class="row">
        <div class="col-md-2">
            Initial Value:
            <input type="number" class="form-control" placeholder="Initial Value" aria-label="Iterations" asp-for="Other.initial">
        </div>

        <div class="col-md-2">
            <label class="input-group-text" for="Other_dist">Distribution</label>
            <div class="input-group">
                <select class="form-select" id="Other_dist" aria-label="Select distribution" asp-for="Other.dist">
                    <option selected value="Constant">Constant</option>
                    <option value="Uniform">Uniform</option>
                    <option value="Triangular">Triangular</option>
                    <option value="Normal">Normal</option>
                    <option value="Lognormal">Lognormal</option>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <label class="input-group-text" for="Other_growth">Growth Type</label>
            <div class="input-group">
                <select class="form-select" id="Other_growth" aria-label="Select Growth" asp-for="Other.growth">
                    <option value="Constant">Constant Growth</option>
                    <option value="Nonconstant">Nonconstant Growth</option>
                    <option selected value="None">No Growth</option>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="mean/min" aria-label="Iterations" asp-for="Other.param1">
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="variance/max" aria-label="Iterations" asp-for="Other.param2">
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control" placeholder="Most Likely" aria-label="Iterations" asp-for="Other.param3">
        </div>
    </div>
    <br />
    <div class="d-grid gap-2">
        <button class="btn btn-primary" type="submit">Run Simulation</button>
    </div>
</form>

<div class="row justify-content-center mt-4">
    <div id="plotlyChart" class="col-md-12"></div>
</div>
@section Scripts {
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.getElementById('dataForm').addEventListener('submit', function (event) {
                event.preventDefault(); // Prevent the form from submitting traditionally

                var formData = new FormData(this);
                // var independentVariableName = "Revenue";
                // var dependentVariableName = "Frequency";

                fetch(this.action, {
                    method: 'POST',
                    body: formData,
                })
                    .then(response => response.json())
                    .then(data => {
                        // Added to print JSON data to check formatting
                        // document.getElementById('jsonResponse').textContent = JSON.stringify(data, null, 2);

                        var xValues = data.Data.Fields[0];
                        var xMin = Math.min(...xValues);
                        var xMax = Math.max(...xValues);
                        // Extend the x-range significantly
                        var xExtension = (xMax - xMin) * 0.5; // Extend by 10% of the range on both sides
                        var extendedXMin = 0;
                        var extendedXMax = xMax + xExtension;

                        // Generate points for the regression line using the extended range

                        var plotData = [{
                            x: xValues,
                            type: 'histogram',
                            name: 'Data Points'
                        }];

                        var layout = {
                            title: "Simulated Revenues",
                            xaxis: { title: "Revenue" },
                            yaxis: { title: "Frequecy" },
                            text: "Confidence Interval" + data.Confidence,
                            annotations: [{
                                x: 0.5,
                                y: 1.13,
                                xref: 'paper',
                                yref: 'paper',
                                showarrow: false,
                                font: { size: 16 }
                            }]
                        };

                        Plotly.newPlot('plotlyChart', plotData, layout);
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        document.getElementById('jsonResponse').textContent = 'Error fetching data: ' + error.toString();
                    });
            });
        });
        document.getElementById('saveGraph').addEventListener('click', function () {
            Plotly.toImage('plotlyChart', { format: 'png' }).then(function (dataUrl) {
                // Send this dataUrl to the server
                fetch('/YourController/SaveGraph', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ imageData: dataUrl })
                })
                    .then(response => response.text())
                    .then(data => {
                        console.log(data); // Handle the server response, e.g., showing a success message
                    })
                    .catch(error => console.error('Error:', error));
            });
        });

    </script>
}