MadisonCountyCollaborationApplication/Pages/AdminDashboard.cshtml.cs
using MadisonCountyCollaborationApplication.Pages.DB;
using MadisonCountyCollaborationApplication.Pages.DataClasses;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MadisonCountyCollaborationApplication.Pages
{
    public class AdminDashboardModel : PageModel
    {
        [BindProperty(SupportsGet = false)]
        public DataClasses.Users NewUser { get; set; }

        [BindProperty(SupportsGet = false)]
        public DataClasses.UserProcess NewUserProcess { get; set; }

        [BindProperty(SupportsGet = false)]
        public string RemoveUserID { get; set; }

        [BindProperty(SupportsGet = false)]
        public string ProcessName { get; set; }

        [BindProperty(SupportsGet = false)]
        public string RemoveProcessID { get; set; }


        public List<SelectListItem> UserList { get; set; }

        public List<SelectListItem> ProcessList { get; set; }

        public List<SelectListItem> UserTypeList { get; set; }

       

    

        public IActionResult OnGetSessionCheck()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                return Page();
            }
            else
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("/User/Login");
            }
        }

        public IActionResult OnGet()
        {

            string username = HttpContext.Session.GetString("username");
            var userID = DBClass.UserNameIDConverter(username);

            bool isAdmin = DBClass.CheckAdmin(userID);

            if (isAdmin)
            {

                UserList = new List<SelectListItem>();

                using (var UserReader = DBClass.GeneralReaderQuery("SELECT * FROM Users"))
                {
                    while (UserReader.Read())
                    {
                        UserList.Add(new SelectListItem
                        {
                            Text = UserReader["userName"].ToString(),
                            Value = UserReader["userID"].ToString()
                        });
                    }
                }

                ProcessList = new List<SelectListItem>();

                using (var ProcessReader = DBClass.GeneralReaderQuery("SELECT * FROM Process"))
                {
                    while (ProcessReader.Read())
                    {
                        ProcessList.Add(new SelectListItem
                        {
                            Text = ProcessReader["processName"].ToString(),
                            Value = ProcessReader["processID"].ToString()
                        });
                    }
                }

                UserTypeList = new List<SelectListItem>();

                UserTypeList.Add(new SelectListItem
                {
                    Text = "System Administrator",
                    Value = "admin"
                });

                UserTypeList.Add(new SelectListItem
                {
                    Text = "Normal User",
                    Value = "normal"
                });

                return Page();
            }
            else
            {
                return RedirectToPage("Home");
            }

        }


        

        public IActionResult OnPostAddProcess()
        {

            string addProcess = $"INSERT INTO Process (processName) VALUES (" + "'" + ProcessName + "'" + ");";

            DBClass.GeneralInsertQuery(addProcess);

            TempData["SuccessMessage"] = ProcessName + "was created successfully!";

            return RedirectToPage("AdminDashboard");
 

        }


        public IActionResult OnPostAddUserToProcess()
        {
            string userIDString = NewUserProcess.UserID.ToString();
            string processIDString = NewUserProcess.ProcessID.ToString();

            var userName = DBClass.UserIDtoName(userIDString);
            var processName = DBClass.ProcessIDtoName(processIDString);

            var exist = DBClass.UserProcessExist(NewUserProcess.UserID, NewUserProcess.ProcessID);
            if (!exist)
            {
                string userProcessQuery = $"INSERT INTO UserProcess (userID, processID) VALUES (" + NewUserProcess.UserID + "," + NewUserProcess.ProcessID + ");";
                DBClass.GeneralInsertQuery(userProcessQuery);

                TempData["SuccessMessage"] = userName + " was successfully added to the " + processName + " process!";

                return RedirectToPage("AdminDashboard");
            }
            else
            {
                TempData["ErrorMessage"] = userName + " already has access to the" + processName + " process";
                return RedirectToPage("AdminDashboard");
            }
        }




        public IActionResult OnPostAddUser()
        {

            DBClass.CreateAndHashUser(NewUser);
            TempData["SuccessMessage"] = NewUser.userName + "'s account was created successfully!";
            return RedirectToPage("AdminDashboard");

        }


        public IActionResult OnPostRemoveUser()
        {

            string removeUserQuery = $"DELETE FROM Users WHERE userID =" + RemoveUserID + ";";
            DBClass.GeneralInsertQuery(removeUserQuery);

            
            var userName = DBClass.UserIDtoName(RemoveUserID);

            TempData["SuccessMessage"] = userName + " has been removed from the system successfully!";
            return RedirectToPage("AdminDashboard");

        }


        public IActionResult OnPostRemoveProcess()
        {
            string removeProcessQuery = $"DELETE FROM Process WHERE processID =" + RemoveProcessID + ";";
            DBClass.GeneralInsertQuery(removeProcessQuery);

            var processName = DBClass.ProcessIDtoName(RemoveProcessID);

            TempData["SuccessMessage"] = "The" + processName + " process has been removed from the system!";
            return RedirectToPage("AdminDashboard");
        }



        public IActionResult OnPostClearInputs()
        {
            ModelState.Clear();
            NewUser = new MadisonCountyCollaborationApplication.Pages.DataClasses.Users();
            return Page();
        }

        public IActionResult OnPostPopulate()
        {
            // Set preset values
            NewUser = new DataClasses.Users
            {
                userName = "TestUsername",
                firstName = "Zack",
                lastName = "Benjamin",
                email = "zackbanjamin@gmail.com",
                phone = "1234567890",
                userType = "Admin",
            };


            return Page(); // Return to the same page with preset values populated
        }




    }
}

MadisonCountyCollaborationApplication/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MadisonCountyCollaborationApplication.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

MadisonCountyCollaborationApplication/Pages/Home.cshtml.cs
using MadisonCountyCollaborationApplication.Pages.DB;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;

namespace MadisonCountyCollaborationApplication.Pages
{
    public class HomeModel : PageModel
    {
        [BindProperty]
        [Required]
        public int ProcessID { get; set; }

        public IActionResult OnPostHome()
        {
            return RedirectToPage("/HomePage");
        }

        public IActionResult OnPostCreate()
        {
            return RedirectToPage("/Process/CreateProcess");
        }

        public IActionResult OnPostSelect()
        {
            if (ProcessID > 0)
            {
                if (DBClass.ProcessExist(ProcessID))
                {
                    HttpContext.Session.SetInt32("processID", ProcessID);
                    DBClass.MainDBconnection.Close();
                    return RedirectToPage("/Process/Index", new { ProcessID = ProcessID }); //routes ProcessID in URL
                }
                else
                {
                    DBClass.MainDBconnection.Close();
                    ViewData["ProcessNotExistMessage"] = "That process does not exist.";
                    return OnGet();
                }
            }
            else
            {
                ViewData["ProcessNotExistMessage"] = "That process does not exist.";
                return OnGet();
            }
        }

        public List<DataClasses.Process> ProcessList { get; set; }

        public HomeModel()
        {
            ProcessList = new List<DataClasses.Process>();
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewData["LoginMessage"] = "Login for " + HttpContext.Session.GetString("username") + " successful!";
                string username = HttpContext.Session.GetString("username");
                var userID = DBClass.UserNameIDConverter(username);

                string sqlQuery = $@"
                    SELECT Process.ProcessID, processName, notesAndInfo
                    FROM Process
                    INNER JOIN UserProcess ON UserProcess.ProcessID = Process.ProcessID
                    WHERE UserProcess.userID = {userID};";

                SqlDataReader processReader = DBClass.GeneralReaderQuery(sqlQuery);
                while (processReader.Read())
                {
                    ProcessList.Add(new DataClasses.Process
                    {
                        ProcessID = processReader.GetInt32(processReader.GetOrdinal("processID")),
                        ProcessName = processReader.GetString(processReader.GetOrdinal("processName")),
                        
                    });
                }

                DBClass.MainDBconnection.Close();
                return Page();
            }
            else
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("/User/Login");
            }
        }
    }
}

MadisonCountyCollaborationApplication/Pages/Index.cshtml.cs
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MadisonCountyCollaborationApplication.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        private static readonly string StorageConnString = "DefaultEndpointsProtocol=https;AccountName=countyconnectstorage;AccountKey=IezvDEewuBWkAsIqls+LxrQUT3OJVxayH/hq4cNwbsP2bEAZDNPFDSQHScxCEZ2dRcBDw+b2PioZ+AStlmc6Xg==;EndpointSuffix=core.windows.net";
        private readonly string DocumentsContainerName = "documents";
        private readonly string DatasetsContainerName = "datasets"; // Assuming datasets are stored here

        private BlobClient GetBlobClient(string documentName)
        {
            // Create a new BlobServiceClient using the storage connection string directly.
            // This mirrors the approach used in your upload method.
            BlobServiceClient blobServiceClient = new BlobServiceClient(StorageConnString);

            // Assuming DocumentsContainerName is a class member that holds the name of your documents container.
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(DocumentsContainerName);

            // Return the BlobClient for the specified document.
            return containerClient.GetBlobClient(documentName);
        }

        public async Task<IActionResult> OnPostDownloadDocumentAsync(string documentName)
        {
            try
            {
                // Use the literal document name from the database, which includes the timestamp
                var blobClient = GetBlobClient(documentName);
                if (await blobClient.ExistsAsync())
                {
                    try
                    {
                        var download = await blobClient.DownloadAsync();
                        var stream = download.Value.Content;
                        var contentType = "application/octet-stream"; // Consider setting the actual content type if known.
                        return File(stream, contentType, documentName);
                    }
                    catch (Exception ex)
                    {
                        // Log the detailed exception
                        // Consider using a logging framework or storing the message in TempData
                        TempData["ErrorMessage"] = $"Error downloading the file: {ex.Message}";
                        return Page();
                    }
                }
                else
                {
                    TempData["ErrorMessage"] = "Document not found in Blob Storage.";
                    return Page();
                }

            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
                return Page();
            }
        }

    }
}

MadisonCountyCollaborationApplication/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MadisonCountyCollaborationApplication.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

MadisonCountyCollaborationApplication/Pages/AdminDashboard.cshtml
@page
@using System.Data.SqlClient
@using MadisonCountyCollaborationApplication.Pages.DB
@model MadisonCountyCollaborationApplication.Pages.AdminDashboardModel
@{
}

<head>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>


    <title>County Connect - Admin Dashboard</title>

    <style>

        #header{text-align: center;}

        .card{
            padding:3%;
            margin: 3%;
            min-height: 200px;
            box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.2);
        }

        
        
    </style>
</head>


<h1 id="header">Admin Dashboard</h1>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

@if (TempData["Error Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Error Message"]
    </div>
}

<div class="container text-center container-md">

    
    
    <div class="row row-1">
        <div class="col">
        <div class="card">
            <h3>Current System Users</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Username</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                    </tr>
                </thead>

                <tbody>
                    @{
                        string userQuery = $"SELECT userID, userName, firstName, lastName FROM Users";
                        SqlDataReader userReader = DBClass.GeneralReaderQuery(userQuery);

                        while (userReader.Read())
                        {
                            <tr>
                                <td>@userReader["userID"].ToString()</td>
                                <td>@userReader["userName"].ToString()</td>
                                <td>@userReader["firstName"].ToString()</td>
                                <td>@userReader["lastName"].ToString()</td>
                            </tr>
                        }
                        userReader.Close();
                    }
                </tbody>

            </table>
        </div>
        </div>
    </div>
    
    
    
    
    <div class="row row-cols-1 row-cols-md-2">
        <div class="col-lg">
            <div class="card">
                <h3>Create a New User</h3>


                <form method="post" asp-page-handler="AddUser">
                    <div class="row">
                        <div class="col">
                            <div class="form-floating mb-3">
                            <input type="text" asp-for="NewUser.userName" class="form-control" id="floatingInput" placeholder="Enter username">
                            <label for="floatingInput">Username</label>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-floating mb-3">
                            <input type="password" asp-for="NewUser.userPassword" class="form-control" id="floatingInput" placeholder="Password">
                            <label for="floatingInput">Password</label>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col">
                            <div class="form-floating mb-3">
                            <input type="text" asp-for="NewUser.firstName" class="form-control" id="floatingInput" placeholder="Enter first name">
                            <label for="floatingInput">First Name</label>
                            </div>
                        </div>
                        <div class="col">
                                <div class="form-floating mb-3">
                            <input type="text" asp-for="NewUser.lastName" class="form-control" id="floatingInput" placeholder="Enter last name">
                            <label for="floatingInput">Last Name</label>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row"></div>
                    <div class="form-group">
                        <div class="form-floating mb-3">
                        <input type="email" asp-for="NewUser.email" class="form-control" id="floatingInput" placeholder="Enter email">
                        <label for="floatingInput">Email Address</label>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="form-floating mb-3">
                        <input type="phone" asp-for="NewUser.phone" class="form-control" id="floatingInput" placeholder="Enter phone number">
                        <label for="floatingInput">Phone Number</label>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col">
                            <select asp-for="NewUser.userType" asp-items="Model.UserTypeList" class="form-select" id="userType">
                                <option value="">Select a User Type</option>
                            </select>
                        </div>
                    <br />
                    </div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-primary">Create User</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-lg">

            <div class="card">
                <h3>Add a User to a Process</h3>
                <div class="row">
                    <form method="post" asp-page-handler="AddUserToProcess">
                        <div class="col">
                            <select asp-for="NewUserProcess.UserID" asp-items="Model.UserList" class="form-select">
                                <option value="">Select a User</option>
                            </select>
                        </div>

                        <div class="col">
                            <select asp-for="NewUserProcess.ProcessID" asp-items="Model.ProcessList" class="form-select">
                                <option value="">Select a Process</option>
                            </select>
                        </div>

                        <br />
                        <input type="submit" value="Add User to Process" class="btn btn-primary" />

                    </form>
                </div>
            </div>

            <div class="card">
                <h3>Remove a User</h3>
                <form method="post" asp-page-handler="RemoveUser">
                    <select asp-for="RemoveUserID" asp-items="Model.UserList" class="form-select">
                        <option value="">Select a User</option>
                    </select>

                    <br />
                    <button type="submit" class="btn btn-primary" data-bs-target="#myModal">Remove User</button>
                </form>
            </div>


        </div>

    </div>
    
    <div class="row justify-content-md-center">

        <!--CREATE PROCESS-->
        <div class="col col-lg">
            <div class="card">
                <h3>Create a New Process</h3>
                <form method="post" asp-page-handler="AddProcess">
                
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="ProcessName" class="form-control" id="floatingInput" placeholder="Process Name" >
                        <label for="floatingInput">Process Name</label>
                    </div>
                    <input type="submit" value="Add Process" class="btn btn-primary" data-bs-target="#myModal" />
                
                </form>
            </div>
        </div>
    
        <!--ADD USER TO PROCESS-->
        <div class="col col-lg">
            <div class="card">
               <h3>Remove a Process</h3>
            
                <form method="post" asp-page-handler="RemoveProcess">
           
            
                    <select asp-for="RemoveProcessID" asp-items="Model.ProcessList" class="form-select">
                        <option value="">Select a Process</option>
                    </select>
            <br />
                    <input type="submit" value="Add User to Process" class="btn btn-primary" />
            
                </form>
            </div>
        </div>
    </div>


</div>

MadisonCountyCollaborationApplication/Pages/Home.cshtml
@page
@model MadisonCountyCollaborationApplication.Pages.HomeModel

@{
    ViewData["Title"] = "My Processes";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<style>
    .header {
        float: right;
        padding: 5%;
    }

    .box-table {
        display: flex;
        flex-wrap: wrap;
        gap: 20px; /* Adds space between cards */
        justify-content: center; /* Centers cards in the container */
    }

    .card {
        flex: 1 1 calc(20% - 20px);
        margin-bottom: 20px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        transition: transform 0.2s;
        padding: 15px;
        border-radius: 5px;
        max-width: 100%;
    }


    .card:hover {
        transform: scale(1.05); /* Scales card on hover */
        cursor: pointer;
    }

    .card-header, .card-body {
        padding: 15px;
    }


</style>

<h2>My Processes</h2>

@* @if (Model.ProcessList.Any())
{
    <form asp-page-handler="Select" method="post" id="processForm">
        <div class="box-table">
            @foreach (var process in Model.ProcessList)
            {
                <div class="card" tabindex="0" role="button" onclick="selectProcess(@process.ProcessID)">
                    <div class="card-body">
                        @process.ProcessName
                    </div>
                    
                </div>
            }
        </div>
        <input type="hidden" name="ProcessID" id="processIdInput" value="" />
    </form>
} *@
@if (Model.ProcessList.Any())
{
    <form asp-page-handler="Select" method="post" id="processForm">
        <div class="container">
            <div class="row">
                @foreach (var process in Model.ProcessList)
                {
                    <div class="col-md-4">
                        <div class="card" tabindex="0" role="button" onclick="selectProcess(@process.ProcessID)">
                            <div class="card-body">
                                @process.ProcessName
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <input type="hidden" name="ProcessID" id="processIdInput" value="" />
    </form>
}

else
{
    <p>No processes found. Please create a new process.</p>
}

@section Scripts {
    <script>
        function selectProcess(processId) {
            document.getElementById('processIdInput').value = processId;
            document.getElementById('processForm').submit();
        }
    </script>
}

MadisonCountyCollaborationApplication/Pages/Index.cshtml
@page
@using System.Data.SqlClient;
@using MadisonCountyCollaborationApplication.Pages.DB;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
     Layout = null;
}

<head>
    
    <title>County Connect - Home</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
    
</head>

<!-- Start Navbar -->
<nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="https://www.madisonco.virginia.gov/" target="_blank">
            <img src="Images/MadCountyBug.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">

        </a>
        <button class="btn btn-primary">
            <a asp-page="/User/Login" class="btn-text">
                Employee Log In
            </a>
        </button>
    </div>
</nav>
<!-- End Navbar -->


<!-- starthero -->
<div class="masthead" style="background-image: url(Images/madheronew.jpg);">

    <div class="color-overlay d-flex justify-content-center align-items-center">
        <h1>Madison County, Virginia</h1>
    </div>
</div>
<!-- endhero -->


<!-- start subnav -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">County Reports</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <!-- budgeting -->
                <li class="nav-item me-5">
                    <a class="nav-link active report-type" style="color: rgb(17, 73, 17);" aria-current="page"><b>Budgeting</b></a>
                </li>
                <!-- budgeting -->
                <!-- revenue -->
                <li class="nav-item me-5">
                    <a asp-page="/PublicView/Revenue" class="nav-link report-type">Revenue Projections</a>
                </li>
                <!-- revenue -->
                <!-- administrative -->
                <li class="nav-item me-5">
                    <a asp-page="/PublicView/Administrative" class="nav-link report-type">Administrative Efficiency</a>
                </li>
                <!-- administrative -->
                <!-- employee -->
                <li class="nav-item me-5">
                    <a asp-page="/PublicView/Management" class="nav-link report-type">Management Efficiency</a>
                </li>
                <!-- employee -->
                <!-- economic -->
                <li class="nav-item me-5">
                    <a asp-page="/PublicView/Economic" class="nav-link report-type">Economic Planning</a>
                </li>
                <!-- economic -->
            </ul>
        </div>
    </div>
</nav>
<!-- end subnav -->
<!-- start sections -->
<div class="report-container">
<h3 class="text-center">Budgeting</h3>
<table class="table table-striped rounded-3 overflow-hidden">
    <thead class="table-color">
        <tr>

            <th scope="col" style="background-color:rgb(17, 73, 17); color: white;">Report Name</th>
            <th scope="col" style="background-color:rgb(17, 73, 17); color: white;">Date Published</th>
            <th scope="col" style="background-color:rgb(17, 73, 17); color: white;">Download</th>
        </tr>
    </thead>
   <tbody>
        @{
            string budgetQuery = $"SELECT Document.documentName, STUFF(documentName, 1, CHARINDEX('_', documentName, CHARINDEX('_', documentName) + 1), '') AS displayName, Document.datePublished FROM Document INNER JOIN DocumentProcess ON Document.documentID = DocumentProcess.documentID WHERE Document.isPublic = 1  AND DocumentProcess.processID = 1;";
            SqlDataReader BudgetReportReader = DBClass.GeneralReaderQuery(budgetQuery);

            while (BudgetReportReader.Read())
            {
                <tr>

                    <td>@BudgetReportReader["displayName"].ToString()</td>
                    <td>@BudgetReportReader["datePublished"].ToString()</td>
                    <td>
                        <!-- Download button form -->
                        <form method="post" asp-page-handler="DownloadDocument">
                            <input type="hidden" name="documentName" value="@BudgetReportReader["documentName"].ToString()" />

                            <button type="submit" class="btn btn-primary btn-sm">
                                <div class="icons">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                                        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5" />
                                        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z" />
                                    </svg>
                                </div>
                                Download
                            </button>
                        </form>
                    </td>

                </tr>
            }
        }
   </tbody>
</table>
</div>